### PR TITLE
Project stats

### PR DESCRIPTION
**Pull request by charliemartin0**
Redesigned Admin Dashboard
Still working on individual project stats but creating a pull request for merging purposes

### CODE REVIEW

**Comment by Kodoh** [comment]
It would be nice to get some visual stats, I would recommend https://www.chartjs.org/

**Comment by charliemartin0** [comment]
> I've sorted a few conflicts between this branch and Master. If you could also do the user dashboard as well that would be great. Also, the to do list doesn't save and is just the text editor?

Yeah i've just made a commit that allows the editor to save in localstorage will make a pr soon

**Comment by charliemartin0** [comment]
> It would be nice to get some visual stats, I would recommend https://www.chartjs.org/

Im working on that now

**Comment by Diacryptic** [comment]
Sounds good. I'll merge now. Also, the dashboard js is split into two now with an adminDashboard.js and a dashboard.js file.

**Review by Diacryptic — APPROVED** [review]

**Pull request merged**
