### PR TITLE
User Interface for Projects

### PR DESCRIPTION
**Pull request by Diacryptic**
Sorry for the loaded PR but as the deadline comes close and we have a lot of unfinished functionality, I think it warrants it.

This PR was to target the user with what they can and can't do on the system. Now, only projects that they are a part of (i.e. have at least one assigned task on) will be presented to them and can be looked at rather than every project like the Admin.

Also, only tasks that the user is assigned to can be edited and other tasks on the project are read only and CANNOT be dragged (I'd like to add a commenting system onto tasks but we'll have to see with time constraints). 

Have a look at the user functionality with the user@make-it-all.com account (password: User1234! if you have forgot) and lmk if it all works.

Future Plans:

- Implement Project Leader Functionality
- Make a delete project button
- Project Deadline Implementation
- Manhours Calculation

image
image

### CODE REVIEW

**Comment by Kodoh** [comment]
image
Not too sure why I see this on a user account

**Comment by Diacryptic** [comment]
image
@Kodoh ?

**Comment by Diacryptic** [comment]
Might be fetching the Admin Dashboard as part of the current page local storage. Try clicking back on the dashboard after going to projects.

**Comment by Kodoh** [comment]
I was on the wrong branch dont worry

**Review by Kodoh — APPROVED** [review]

**Pull request merged**
